### ISSUE TITLE
everything works sort of

### ISSUE THREAD

**Issue by outoftrun** [KrzysztofZurek1973/webthings-components#2]
Everything builds ok it links to my hub however what comes out is a json listing rather than an html one
Not sure what I am doing wrong

===============================================================================
[{"name":"RGB line","href":"/0","@context":"https://webthings.io/schemas","@type":["Light"],"properties":{"on":{"@type":"OnOffProperty","title":"ON/OFF","type":"boolean","description":"ON/OFF","readOnly":false,"links":[{"rel":"property","href":"/0/properties/on"}]},"diodes":{"@type":"LevelProperty","title":"diodes","type":"integer","description":"number of controlled diodes","minimum":3,"maximum":1000,"unit":"pcs","readOnly":false,"links":[{"rel":"property","href":"/0/properties/diodes"}]},"pattern":{"@type":"PatternProperty","title":"pattern","type":"string","enum":["Running point","Rgb palette","Tetris","Static","Floating ends","New Year","Christmas"],"description":"current color pattern","readOnly":false,"links":[{"rel":"property","href":"/0/properties/pattern"}]},"color":{"@type":"ColorProperty","title":"color","type":"string","description":"color set for some patterns","unit":"color RGB","readOnly":false,"links":[{"rel":"property","href":"/0/properties/color"}]},"speed":{"@type":"LevelProperty","title":"speed","type":"integer","description":"led refreshment speed","minimum":1,"maximum":100,"unit":"percent","readOnly":false,"links":[{"rel":"property","href":"/0/properties/speed"}]},"brgh":{"@type":"BrightnessProperty","title":"brightness","type":"integer","description":"led line brightness","minimum":0,"maximum":100,"unit":"percent","readOnly":false,"links":[{"rel":"property","href":"/0/properties/brgh"}]}},"actions":{},"events":{},"links":[{"rel":"properties","href":"/0/properties"},{"rel":"actions","href":"/0/actions"},{"rel":"events","href":"/0/events"},{"rel":"alternate","href":"ws://ESP32.local:8080/0"}],"description":"web connected color leds"}]

**Comment by KrzysztofZurek1973** [comment]
json is the format sent by WebThing to the client, it is send in html message when you send GET (in html) of the main directory of the thing.
For example you have WebThing rgb-lamp, when you send "GET /" to the rgb-lamp.local:8080 the WebThing sends its specification in json format (as attached above).
Format of all communication is available here: https://webthings.io/api/#thing-resource.
